#!/bin/bash

# Nome do tema
THEME="catppuccin"

# Esquemas possíveis
LIGHT="latte"
DARK="frappe"

# Obtém o esquema atual
CURRENT_SCHEME=$(spicetify config color_scheme | cut -d ' ' -f2)

# Alterna entre latte e frappe
if [[ "$CURRENT_SCHEME" == "$LIGHT" ]]; then
    NEW_SCHEME="$DARK"
else
    NEW_SCHEME="$LIGHT"
fi

# Aplica as configurações
spicetify config current_theme "$THEME"
spicetify config color_scheme "$NEW_SCHEME"
spicetify config inject_css 1 inject_theme_js 1 replace_colors 1 overwrite_assets 1
spicetify apply

notify-send -t 3000 -i spotify "🎨 Spicetify" "Tema: $NEW_SCHEME"

